using System.Collections.Generic;

namespace AggroRangeVisualizer
{
    public class DeepData
    {
        public class MobData
        {
            public enum ThreatLevel
            {
                Unspecified,
                Easy,
                Caution,
                Dangerous,
                Vicious
            }
            public ThreatLevel Threat { get; set; }

            public enum AggroType
            {
                Unspecified,
                Sight,
                Sound,
                Proximity,
                Boss
            }
            public AggroType Aggro { get; set; }
            
        }

        public static MobData Mobs(uint nameID)
        {
            if (mobs.TryGetValue(nameID, out MobData value)) return value;
            else return null;
        }

        private static readonly Dictionary<uint, MobData> mobs = new Dictionary<uint, MobData>()
            {
				// HoH floors 1-9
                { 7262, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7263, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7264, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7265, new MobData { Threat=MobData.ThreatLevel.Dangerous, Aggro=MobData.AggroType.Proximity} },
                { 7266, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 7267, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7268, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7269, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 7270, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7271, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7272, new MobData { Threat=MobData.ThreatLevel.Dangerous, Aggro=MobData.AggroType.Sight} },
                { 7273, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 7274, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
				// HoH floors 11-19
                { 7275, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7276, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 7277, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7278, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7279, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 7280, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 7281, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 7282, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7283, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7284, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7285, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 7286, new MobData { Threat=MobData.ThreatLevel.Dangerous, Aggro=MobData.AggroType.Sight} },
                { 7287, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
				// HoH floors 21-29
                { 7288, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 7289, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7290, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 7291, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7292, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Proximity} },
                { 7293, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7294, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7295, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Proximity} },
                { 7296, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7297, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sound} },
                { 7298, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7299, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7300, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} }, 
                //HoH floors 31-39
                { 7301, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7302, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7303, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 7304, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 7305, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 7306, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7307, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7308, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7309, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7310, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 7311, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 7312, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 7313, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
				// HoH floors 41-49
                { 7314, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 7315, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 7316, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7317, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7318, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 7319, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 7320, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 7321, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7322, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7323, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7324, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 7325, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7326, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sound} },
				//HoH floors 51-59
                { 7327, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sound} },
                { 7328, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sound} },
                { 7329, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 7330, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 7331, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7332, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Proximity} },
                { 7333, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7334, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7335, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7336, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 7337, new MobData { Threat=MobData.ThreatLevel.Dangerous, Aggro=MobData.AggroType.Sight} },
                { 7338, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7339, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
				// HoH floors 61-69
                { 7340, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sound} },
                { 7341, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 7342, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7343, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Proximity} },
                { 7344, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sound} },
                { 7345, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7346, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 7347, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 7348, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7349, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 7350, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 7351, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
				// HoH floors 71-79
                { 7352, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7353, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Proximity} },
                { 7354, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7355, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 7356, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 7357, new MobData { Threat=MobData.ThreatLevel.Dangerous, Aggro=MobData.AggroType.Sight} },
                { 7358, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 7359, new MobData { Threat=MobData.ThreatLevel.Dangerous, Aggro=MobData.AggroType.Proximity} },
                { 7360, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 7361, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 7362, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 7363, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7364, new MobData { Threat=MobData.ThreatLevel.Dangerous, Aggro=MobData.AggroType.Sight} },
				// HoH floors 81-89
				{ 7365, new MobData { Threat=MobData.ThreatLevel.Dangerous, Aggro=MobData.AggroType.Proximity} },
                { 7366, new MobData { Threat=MobData.ThreatLevel.Dangerous, Aggro=MobData.AggroType.Sight} },
                { 7367, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7368, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 7369, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7370, new MobData { Threat=MobData.ThreatLevel.Dangerous, Aggro=MobData.AggroType.Sight} },
                { 7371, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 7372, new MobData { Threat=MobData.ThreatLevel.Dangerous, Aggro=MobData.AggroType.Sight} },
                { 7373, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 7374, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 7375, new MobData { Threat=MobData.ThreatLevel.Dangerous, Aggro=MobData.AggroType.Sight} },
                { 7376, new MobData { Threat=MobData.ThreatLevel.Dangerous, Aggro=MobData.AggroType.Sight} },
                { 7377, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
				// HoH floors 91-99
                { 7378, new MobData { Threat=MobData.ThreatLevel.Vicious, Aggro=MobData.AggroType.Sight} },
                { 7379, new MobData { Threat=MobData.ThreatLevel.Dangerous, Aggro=MobData.AggroType.Sight} },
                { 7380, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7381, new MobData { Threat=MobData.ThreatLevel.Dangerous, Aggro=MobData.AggroType.Proximity} },
                { 7382, new MobData { Threat=MobData.ThreatLevel.Dangerous, Aggro=MobData.AggroType.Sight} },
                { 7383, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 7384, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7385, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Proximity} },
                { 7386, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 7387, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 7388, new MobData { Threat=MobData.ThreatLevel.Dangerous, Aggro=MobData.AggroType.Sight} },
                { 7389, new MobData { Threat=MobData.ThreatLevel.Dangerous, Aggro=MobData.AggroType.Sight} },
                { 7390, new MobData { Threat=MobData.ThreatLevel.Dangerous, Aggro=MobData.AggroType.Sight} },
                { 7391, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 7584, new MobData { Threat=MobData.ThreatLevel.Dangerous, Aggro=MobData.AggroType.Sight} }, 
                // HoH bosses and misc.
                { 7392, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Proximity} },
                { 7393, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Proximity} },
                { 7394, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Proximity} },
                { 7478, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Boss} },
                { 7480, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Boss} },
                { 7481, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Boss} },
                { 7483, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Boss} },
                { 7485, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Boss} },
                { 7487, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Boss} },
                { 7489, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Boss} },
                { 7490, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Boss} },
                { 7493, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Boss} },
                { 7610, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },

                //PotD data
                //PotD 1-10
                { 4975, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 4976, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 4977, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sound} },
                { 4978, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 4979, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 4980, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 4981, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Proximity} },
                { 4982, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sound} },
                { 4983, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 4984, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 4985, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 4986, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Boss} },
                //PotD 11-20
                { 4987, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 4988, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 4989, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 4990, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sound} },
                { 4991, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sound} },
                { 4992, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sound} },
                { 4993, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 4994, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 4995, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 4996, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 4997, new MobData { Threat=MobData.ThreatLevel.Dangerous, Aggro=MobData.AggroType.Sight} },
                { 4998, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 4999, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Boss} },
                //PotD 21-30
                { 5000, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5001, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5002, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5003, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5004, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5005, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5006, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5007, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5008, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5009, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sound} },
                { 5010, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 5011, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sound} },
                { 5012, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Boss} },
                //PotD 31-40
                { 5013, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5014, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sound} },
                { 5015, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5016, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5017, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5018, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5019, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5020, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5021, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5022, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 5023, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5024, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5025, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Boss} },
                // PotD 41-50
                { 5026, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5027, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5028, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5029, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5030, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sound} },
                { 5031, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5032, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Proximity} },
                { 5033, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5034, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5035, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5036, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5037, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sound} },
                { 5038, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Boss} },
                // PotD special NPCs and misc.
                { 5039, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5040, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5041, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5046, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 5047, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 5048, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 5049, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 5050, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 5051, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 5052, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 5053, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 5283, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 5284, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 5285, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 5286, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 5287, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 5288, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 5289, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 5290, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 5291, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 5292, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 5293, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 5294, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 5295, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 5296, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 5297, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 5298, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                // PotD 51-60
                { 5299, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5300, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5301, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5302, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5303, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5304, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5305, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5306, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5307, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5308, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5309, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Boss} },
                // PotD 61-70
                { 5311, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5312, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5313, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5314, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5315, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5316, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5317, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5318, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5319, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5320, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5321, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Boss} },
                // PotD 71-80
                { 5322, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5323, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5324, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5325, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5326, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5327, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5328, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5329, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5330, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5331, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5332, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5333, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Boss} },
                // PotD 81-90
                { 5334, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 5335, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sound} },
                { 5336, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5337, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5338, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sound} },
                { 5339, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5340, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sound} },
                { 5341, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5342, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5343, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5344, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5345, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Boss} },
                // PotD 91-100
                { 5346, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5347, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5348, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5349, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5350, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sound} },
                { 5351, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sound} },
                { 5352, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Proximity} },
                { 5353, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5354, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5355, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sound} },
                { 5356, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Boss} },
                // PotD 101-110
                { 5360, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5361, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5362, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5363, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5364, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Proximity} },
                { 5365, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5366, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Proximity} },
                { 5367, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sound} },
                { 5368, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5369, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5370, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5371, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Boss} },
                // PotD 111-120
                { 5372, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5373, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5374, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 5375, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sound} },
                { 5376, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sound} },
                { 5377, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sound} },
                { 5378, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5379, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sound} },
                { 5380, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Proximity} },
                { 5381, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5382, new MobData { Threat=MobData.ThreatLevel.Dangerous, Aggro=MobData.AggroType.Sight} },
                { 5383, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5384, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Boss} },
                // PotD 121-130
                { 5385, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5386, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5387, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5388, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5389, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Proximity} },
                { 5390, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5391, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5392, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5393, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5394, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sound} },
                { 5395, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 5396, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sound} },
                { 5397, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Boss} },
                // PotD 131-140
                { 5398, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sound} },
                { 5399, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sound} },
                { 5400, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5401, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5402, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 5403, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5404, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5405, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5406, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5407, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5408, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5409, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Proximity} },
                { 5410, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Boss} },
                // PotD 141-150
                { 5411, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5412, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5413, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 5414, new MobData { Threat=MobData.ThreatLevel.Dangerous, Aggro=MobData.AggroType.Sight} },
                { 5415, new MobData { Threat=MobData.ThreatLevel.Dangerous, Aggro=MobData.AggroType.Proximity} },
                { 5416, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sound} },
                { 5417, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5418, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5419, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5420, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5421, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5422, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Proximity} },
                { 5423, new MobData { Threat=MobData.ThreatLevel.Dangerous, Aggro=MobData.AggroType.Sound} },
                { 5424, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Boss} },
                // PotD 151-160
                { 5429, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 5430, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5431, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5432, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5433, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5434, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5435, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5436, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5437, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Proximity} },
                { 5438, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Boss} },
                // PotD 161-170
                { 5439, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5440, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5441, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Proximity} },
                { 5442, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Proximity} },
                { 5443, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 5444, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5445, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5446, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5447, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5448, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Proximity} },
                { 5449, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Boss} },
                // PotD 171-180
                { 5450, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 5451, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 5452, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5453, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 5454, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Proximity} },
                { 5455, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5456, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5457, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5458, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 5459, new MobData { Threat=MobData.ThreatLevel.Vicious, Aggro=MobData.AggroType.Sight} },
                { 5460, new MobData { Threat=MobData.ThreatLevel.Dangerous, Aggro=MobData.AggroType.Sight} },
                { 5461, new MobData { Threat=MobData.ThreatLevel.Dangerous, Aggro=MobData.AggroType.Boss} },
                // PotD 181-190
                { 5462, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sight} },
                { 5463, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sound} },
                { 5464, new MobData { Threat=MobData.ThreatLevel.Vicious, Aggro=MobData.AggroType.Sight} },
                { 5465, new MobData { Threat=MobData.ThreatLevel.Dangerous, Aggro=MobData.AggroType.Sound} },
                { 5466, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Sight} },
                { 5467, new MobData { Threat=MobData.ThreatLevel.Dangerous, Aggro=MobData.AggroType.Sound} },
                { 5468, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5469, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sound} },
                { 5470, new MobData { Threat=MobData.ThreatLevel.Vicious, Aggro=MobData.AggroType.Proximity} },
                { 5471, new MobData { Threat=MobData.ThreatLevel.Dangerous, Aggro=MobData.AggroType.Boss} },
                // PotD 191-200
                { 5472, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sound} },
                { 5473, new MobData { Threat=MobData.ThreatLevel.Dangerous, Aggro=MobData.AggroType.Sight} },
                { 5474, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 5475, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Proximity} },
                // PotD misc.
                { 5479, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Sound} },
                { 5480, new MobData { Threat=MobData.ThreatLevel.Easy, Aggro=MobData.AggroType.Proximity} },
                { 2566, new MobData { Threat=MobData.ThreatLevel.Caution, Aggro=MobData.AggroType.Proximity} },

            };
    }
}
